COMMAND_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
AUDIO_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
RAW_ENABLE = no
NKRO_ENABLE = no
PROGRAMMABLE_BUTTON_ENABLE = yes

SRC+= calculator.c macros.c led_control.c
