/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
#undef ORYX_CONFIGURATOR
#undef TAPPING_TERM
#define TAPPING_TERM 150

#define LAYER_STATE_8BIT // for 8 layers, change to 16 for 16 layers when I use more than 8. (reduces firmware size)

// #undef MOUSEKEY_INTERVAL
// #define MOUSEKEY_INTERVAL 10

// #undef MOUSEKEY_MAX_SPEED
// #define MOUSEKEY_MAX_SPEED 2

// #undef MOUSEKEY_TIME_TO_MAX
// #define MOUSEKEY_TIME_TO_MAX 1

// #undef MOUSEKEY_WHEEL_MAX_SPEED
// #define MOUSEKEY_WHEEL_MAX_SPEED 1

// #undef MOUSEKEY_WHEEL_TIME_TO_MAX
// #define MOUSEKEY_WHEEL_TIME_TO_MAX 1

// #undef MOUSEKEY_WHEEL_MAX_SPEED
// #define MOUSEKEY_WHEEL_MAX_SPEED 1

// #undef MOUSEKEY_WHEEL_INTERVAL
// #define MOUSEKEY_WHEEL_INTERVAL 50

#define MK_3_SPEED
#define MK_W_OFFSET_UNMOD 1
#define MK_W_INTERVAL_UNMOD 20

#define MK_C_OFFSET_UNMOD 10 //Cursor offset per movement (unmodified)
#define MK_C_INTERVAL_UNMOD 16 //Time between cursor movements (unmodified)
#define MK_C_OFFSET_0 2 //Cursor offset per movement (KC_ACL0)
#define MK_C_INTERVAL_0	16 //Time between cursor movements (KC_ACL0)
#define MK_C_OFFSET_1 10 //Cursor offset per movement (KC_ACL1)
#define MK_C_INTERVAL_1	16 //Time between cursor movements (KC_ACL1)
#define MK_C_OFFSET_2 32 //Cursor offset per movement (KC_ACL2)
#define MK_C_INTERVAL_2	16 //Time between cursor movements (KC_ACL2)


// my defines

//#define BACKLIGHT_BREATHING
//#define BREATHING_PERIOD 6
#undef NO_DEBUG
#define NO_DEBUG

#undef NO_PRINT
#define NO_PRINT

// force nkro
//#define FORCE_NKRO

// Leader key defines
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 500

//combos
//#define COMBO_COUNT 26
#define COMBO_COUNT 24
#define COMBO_TERM 30
//#define EXTRA_EXTRA_LONG_COMBOS

//dynamic macros. 128 is default but we don't have not enough ram
//#define DYNAMIC_MACRO_NO_NESTING
//#define DYNAMIC_MACRO_SIZE 64

#define CAPS_WORD_IDLE_TIMEOUT 3000  // https://docs.qmk.fm/#/feature_caps_word?id=customizing-caps-word

// disable all rgb effects lol //decreased firmware size by a bit
//#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE

#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN

#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
